/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tallermecanica;

import java.awt.Frame;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import tallermecanica.Modals.AddNewVehiculoModal;
import tallermecanica.Models.ClienteModel;
import tallermecanica.Models.VehiculoModel;

/**
 *
 * @author adrian
 */
public class CrudAutoMovil extends javax.swing.JInternalFrame {

    DefaultTableModel dm;
    private VehiculoModel vm;
    private ClienteModel cm;

    /**
     * Creates new form CrudAutoMovil
     *
     * @throws java.lang.ClassNotFoundException
     */
    public CrudAutoMovil() throws ClassNotFoundException, SQLException {
        initComponents();
        vm = new VehiculoModel();
        cm = new ClienteModel();
        loadDataVehiculo();
        cargarCBMarca();
    }

    public void loadDataVehiculo() {
        String titles[] = {"Patente", "Marca", "Modelo", "Color", "AÑo", "Cliente", "Fecha Registro"};
        dm = new DefaultTableModel(titles, 0);

        try {
            ResultSet data = vm.viewVehiculo();
            if (data.next()) {
                data.beforeFirst(); // regresa al inicio para no perder el 1 er dato
                while (data.next()) {
                    String patente = (String) data.getString("patenteVehiculo");
                    String marca = (String) data.getString("nombreMarca");
                    String modelo = (String) data.getString("modelo");
                    String color = (String) data.getString("color");
                    String year = (String) data.getString("yearVehiculo");
                    String fecha = (String) data.getString("fechaRegistroVehiculo");
                    String nCliente = (String) data.getString("nombresCliente") + " " + (String) data.getString("apellidosCliente");
                    Object dataAll[] = {patente, marca, modelo, color, year, nCliente, fecha};
                    dm.addRow(dataAll);
                }
                this.dataTableVehiculos.setModel(dm);
            } else {
                JOptionPane.showMessageDialog(null, "No hay datos de Vehiculos", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainCrudVehiculo = new javax.swing.JPopupMenu();
        jmEliminar = new javax.swing.JMenuItem();
        jmEditar = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataTableVehiculos = new javax.swing.JTable();
        btnRefresh = new javax.swing.JButton();
        btnAddNewVehiculo = new javax.swing.JButton();
        panelDatosVehiculo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtModelo = new javax.swing.JTextField();
        jcMarca = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jtColor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtYear = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtRutCliente = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        panelPatente = new javax.swing.JPanel();
        jlPatente = new javax.swing.JLabel();

        jmEliminar.setText("Eliminar");
        jmEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmEliminarActionPerformed(evt);
            }
        });
        mainCrudVehiculo.add(jmEliminar);

        jmEditar.setText("Editar");
        jmEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmEditarActionPerformed(evt);
            }
        });
        mainCrudVehiculo.add(jmEditar);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Mantenedor AutoMovil");
        setPreferredSize(new java.awt.Dimension(1250, 539));
        setRequestFocusEnabled(false);

        dataTableVehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        dataTableVehiculos.setComponentPopupMenu(mainCrudVehiculo);
        jScrollPane1.setViewportView(dataTableVehiculos);

        btnRefresh.setText("Refrescar Tabla");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnAddNewVehiculo.setText("Agregar Nuevo");
        btnAddNewVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewVehiculoActionPerformed(evt);
            }
        });

        panelDatosVehiculo.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Vehiculos"));

        jLabel1.setText("Marca");

        jLabel2.setText("Modelo");

        jcMarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));

        jLabel4.setText("color");

        jLabel5.setText("Año");

        jLabel3.setText("Rut Cliente");

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        jButton1.setText("Verificar Cliente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDatosVehiculoLayout = new javax.swing.GroupLayout(panelDatosVehiculo);
        panelDatosVehiculo.setLayout(panelDatosVehiculoLayout);
        panelDatosVehiculoLayout.setHorizontalGroup(
            panelDatosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosVehiculoLayout.createSequentialGroup()
                .addGroup(panelDatosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDatosVehiculoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18))
                    .addGroup(panelDatosVehiculoLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(panelDatosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(12, 12, 12)))
                .addGroup(panelDatosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDatosVehiculoLayout.createSequentialGroup()
                        .addGroup(panelDatosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDatosVehiculoLayout.createSequentialGroup()
                                .addGroup(panelDatosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtYear)
                                    .addComponent(jcMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)
                                .addGroup(panelDatosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jtRutCliente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelDatosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtModelo)
                            .addComponent(jtColor, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(btnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(348, 348, 348))
        );
        panelDatosVehiculoLayout.setVerticalGroup(
            panelDatosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosVehiculoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panelDatosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jcMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(panelDatosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(28, 28, 28)
                .addGroup(panelDatosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtRutCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(24, 24, 24)
                .addComponent(btnActualizar)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        panelPatente.setBorder(javax.swing.BorderFactory.createTitledBorder("Patente"));
        panelPatente.setToolTipText("");

        jlPatente.setFont(new java.awt.Font("Dialog", 1, 60)); // NOI18N
        jlPatente.setText("000000");

        javax.swing.GroupLayout panelPatenteLayout = new javax.swing.GroupLayout(panelPatente);
        panelPatente.setLayout(panelPatenteLayout);
        panelPatenteLayout.setHorizontalGroup(
            panelPatenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPatenteLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jlPatente)
                .addContainerGap(135, Short.MAX_VALUE))
        );
        panelPatenteLayout.setVerticalGroup(
            panelPatenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPatenteLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jlPatente)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRefresh)
                .addGap(18, 18, 18)
                .addComponent(btnAddNewVehiculo)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelDatosVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(panelPatente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(33, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefresh)
                    .addComponent(btnAddNewVehiculo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(panelDatosVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(panelPatente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        loadDataVehiculo();
        JOptionPane.showMessageDialog(null, "Tabla Actualizada!", "success", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnAddNewVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewVehiculoActionPerformed
        // TODO add your handling code here:
        try {
            Frame f = new Frame();
            AddNewVehiculoModal av;
            av = new AddNewVehiculoModal(f, true);
            av.setVisible(true);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(CrudAutoMovil.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnAddNewVehiculoActionPerformed

    /**
     * TODO Eliminar vehiculo
     *
     * @param evt
     */
    private void jmEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmEliminarActionPerformed
        // TODO add your handling code here:
        try {
            int reg = this.dataTableVehiculos.getSelectedRow();
            String patente = (String) this.dataTableVehiculos.getValueAt(reg, 0);
            int confirm = JOptionPane.showConfirmDialog(null, "¿Estas seguro de eliminarlo?", "Warning", JOptionPane.WARNING_MESSAGE);
            if (JOptionPane.OK_OPTION == confirm) {
                vm.deleteVehiculo(patente);
                JOptionPane.showMessageDialog(null, "Eliminado con exito!", "Success", JOptionPane.INFORMATION_MESSAGE);
                loadDataVehiculo();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jmEliminarActionPerformed

    /**
     * TODO actualizar registro del vehiculo
     *
     * @param evt
     */
    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        String patente = this.jlPatente.getText();
        int marca = 2; // de momento =)
        String modelo = this.jtModelo.getText();
        String color = this.jtColor.getText();
        String year = this.jtYear.getText();
        String rut = this.jtRutCliente.getText();
        if (modelo.equals("")) {
            JOptionPane.showMessageDialog(null, "Modelo Requerido!", "Error", JOptionPane.ERROR_MESSAGE);
            this.jtModelo.requestFocus();
        } else if (color.equals("")) {
            JOptionPane.showMessageDialog(null, "Color Requerido!", "Error", JOptionPane.ERROR_MESSAGE);
            this.jtColor.requestFocus();
        } else if (year.equals("")) {
            JOptionPane.showMessageDialog(null, "Año Requerido!", "Error", JOptionPane.ERROR_MESSAGE);
            this.jtYear.requestFocus();
        } else if (rut.equals("")) {
            JOptionPane.showMessageDialog(null, "Modelo Requerido!", "Error", JOptionPane.ERROR_MESSAGE);
            this.jtRutCliente.requestFocus();
        } else {
            try {
                ResultSet vRut;
                vRut = cm.verificarRutExistente(rut);
                if (vRut.next()) {
                    vRut.beforeFirst();
                    vm.updateVehiculo(patente, marca, modelo, color, Integer.parseInt(year), rut);
                    JOptionPane.showMessageDialog(null, "Actualizados Correctamente", "Success", JOptionPane.INFORMATION_MESSAGE);
                    loadDataVehiculo();
                } else {
                    JOptionPane.showMessageDialog(null, "Rut No Registrado!", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException ex) {
                Logger.getLogger(CrudAutoMovil.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    /**
     * TODO para cargar la informacion en los cajones de texto de edicion
     *
     * @param evt
     */
    private void jmEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmEditarActionPerformed
        // TODO add your handling code here:
        int registro = this.dataTableVehiculos.getSelectedRow();
        String patente = (String) this.dataTableVehiculos.getValueAt(registro, 0);
        try {
            ResultSet vData = vm.viewDataVehiculo(patente);
            if (vData.next()) {
                vData.beforeFirst();
                while (vData.next()) {
                    this.jlPatente.setText(vData.getString("patenteVehiculo"));
                    this.jtModelo.setText(vData.getString("modelo"));
                    this.jtColor.setText(vData.getString("color"));
                    this.jtYear.setText(vData.getString("yearVehiculo"));
                    this.jtRutCliente.setText(vData.getString("clientes_rutCliente"));
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(CrudAutoMovil.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jmEditarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * TODO cargar la marca de los vehiculos en combobox
     *
     * @throws SQLException
     */
    public void cargarCBMarca() throws SQLException {
        try {
            ResultSet vMarca = vm.viewMarca();
            if (vMarca.next()) {
                vMarca.beforeFirst();
                while (vMarca.next()) {
                    this.jcMarca.addItem(vMarca.getString("nombreMarca"));
                }
            } else {
                JOptionPane.showMessageDialog(null, "No hay registro de marca", "Warning!", JOptionPane.WARNING_MESSAGE);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAddNewVehiculo;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JTable dataTableVehiculos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcMarca;
    private javax.swing.JLabel jlPatente;
    private javax.swing.JMenuItem jmEditar;
    private javax.swing.JMenuItem jmEliminar;
    private javax.swing.JTextField jtColor;
    private javax.swing.JTextField jtModelo;
    private javax.swing.JTextField jtRutCliente;
    private javax.swing.JTextField jtYear;
    private javax.swing.JPopupMenu mainCrudVehiculo;
    private javax.swing.JPanel panelDatosVehiculo;
    private javax.swing.JPanel panelPatente;
    // End of variables declaration//GEN-END:variables
}
