/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biblioteca;

import java.awt.Frame;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author adrian
 */
public class Mostrar extends javax.swing.JInternalFrame {

    Principal p = new Principal();
    DefaultTableModel ml;

    /**
     * Creates new form Mostrar
     */
    public Mostrar() {
        initComponents();
        llenarTablaInit();
        llenarTabla();

    }

    public void llenarTabla() {
        Object titulos[] = {"Nombre", "Fecha Nacimiento", "Genero", "Reseña"};
        ml = new DefaultTableModel(titulos, 0);
        Object[] data = new Object[4];
        for (int i = 0; i < Principal.autorData.size(); i++) {
            data[0] = Principal.autorData.get(i).getFechaNacimiento();
            data[1] = Principal.autorData.get(i).getNombre();
            data[2] = Principal.autorData.get(i).getGenero();
            data[3] = Principal.autorData.get(i).getResena();
            ml.addRow(data);
        }
        this.jTDataAutor.setModel(ml);
    }

    public void llenarTablaInit() {
        String nombre, fechaNacimiento, genero, resena;
        for (int i = 0; i < 10; i++) {
            nombre = "alice";
            fechaNacimiento = "10/08/45";
            genero = "FEMENINO";
            resena = "esto es un ejemplo de reseña";
            Autor data = new Autor(Genero.valueOf(genero), resena, fechaNacimiento, nombre);
            Principal.autorData.add(data);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuTabla = new javax.swing.JPopupMenu();
        cargar = new javax.swing.JMenuItem();
        editar = new javax.swing.JMenuItem();
        eliminar = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTDataAutor = new javax.swing.JTable();

        cargar.setText("Cargar Datos");
        cargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarActionPerformed(evt);
            }
        });
        menuTabla.add(cargar);

        editar.setText("Editar Registro");
        editar.setComponentPopupMenu(menuTabla);
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });
        menuTabla.add(editar);

        eliminar.setText("Eliminar Registro");
        eliminar.setComponentPopupMenu(menuTabla);
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        menuTabla.add(eliminar);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Mostrar Datos");

        jTDataAutor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTDataAutor.setComponentPopupMenu(menuTabla);
        jScrollPane1.setViewportView(jTDataAutor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(209, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cargarActionPerformed

    public void editarDatos() {
        try {
            int registro = this.jTDataAutor.getSelectedRow();
            String name = (String) this.jTDataAutor.getValueAt(registro, 0);
            String fechaNacimiento = (String) this.jTDataAutor.getValueAt(registro, 1);
            //String genero = (String) this.jTDataAutor.getValueAt(registro, 2);
            //Genero g = Genero.valueOf(genero);
            System.out.println(fechaNacimiento);
            String resena = (String) this.jTDataAutor.getValueAt(registro, 3);
            Frame f = JOptionPane.getFrameForComponent(this);
            EditarForm e = new EditarForm(f, true, name, fechaNacimiento, resena);
            e.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
        // TODO add your handling code here:
        editarDatos();
    }//GEN-LAST:event_editarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        // TODO add your handling code here:
        try {
            int resp = JOptionPane.showConfirmDialog(null, "¿Estas seguto de eliminar?");
            if (JOptionPane.OK_OPTION == resp) {
                JOptionPane.showMessageDialog(null, "eliminado con exito");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_eliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cargar;
    private javax.swing.JMenuItem editar;
    private javax.swing.JMenuItem eliminar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTDataAutor;
    private javax.swing.JPopupMenu menuTabla;
    // End of variables declaration//GEN-END:variables
}
