package sistemaregistrogaudi.gui;

import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import sistemaregistrogaudi.arte.Arte;
import sistemaregistrogaudi.arte.Autor;
import sistemaregistrogaudi.vendor.Encargado;
import sistemaregistrogaudi.vendor.Sala;

/**
 *
 * @author adrian
 */
public final class App extends javax.swing.JFrame {

    public static HashMap<String, Autor> dataAutor = new HashMap<>();
    public static HashMap<String, Sala> dataSala = new HashMap<>();
    //public static HashMap<Integer, Arte> dataArte = new HashMap<>();
    public static ArrayList<Arte> dataArte = new ArrayList<>();
    /**
     * Creates new form App
     */
    public App() {
        initComponents();
        addDataAutor();
        addDataSala();
    }
    
    /**
     * TODO Cargar Datos en el hasmap de dataAutor;;
     */
    public void addDataAutor() {
        dataAutor.put("1", new Autor("Chileno", "Adrian", "Verdugo", "1"));
        dataAutor.put("2", new Autor("Peruano", "Luis", "Diaz", "2"));
        dataAutor.put("3", new Autor("Boliviano", "Juan", "Perez", "3"));
    }
    
    /**
     * TODO cargar datos de la sala;;
     *  private String nombreSala;
        private int cantidadLampara;
        private int temperatura;
        private String cierreCentralizado;
        private String alarmaIncendio;
        private Encargado encargado;
     */
    public  void addDataSala() {
        Encargado e1 = new Encargado("Programador", 2018, "Juan", "verdugo", "273");
        Encargado e2 = new Encargado("Programador", 2018, "Pedro", "verdugo", "273");
        Encargado e3 = new Encargado("Programador", 2018, "Karen", "verdugo", "273");
        Encargado e4 = new Encargado("Programador", 2018, "Rosa", "verdugo", "273");
        
        dataSala.put("sala uno", new Sala("sala uno", 5, 6, "Si", "No", e1));
        dataSala.put("sala dos", new Sala("sala dos", 5, 6, "Si", "No", e2));
        dataSala.put("sala tres", new Sala("sala tres", 5, 6, "Si", "No", e3));
        dataSala.put("sala cuatro", new Sala("sala cuatro", 5, 6, "Si", "No", e4));
    }   
    
    public static void viewArte() {
        for (int i = 0; dataArte.size() < 10; i++) {
            System.out.println(dataArte.get(i).getId());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainDeskpot = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mainObraArte = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout mainDeskpotLayout = new javax.swing.GroupLayout(mainDeskpot);
        mainDeskpot.setLayout(mainDeskpotLayout);
        mainDeskpotLayout.setHorizontalGroup(
            mainDeskpotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1001, Short.MAX_VALUE)
        );
        mainDeskpotLayout.setVerticalGroup(
            mainDeskpotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 504, Short.MAX_VALUE)
        );

        jMenu1.setText("Opciones");

        mainObraArte.setText("Ingreso Obra de Arte");
        mainObraArte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainObraArteActionPerformed(evt);
            }
        });
        jMenu1.add(mainObraArte);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainDeskpot)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainDeskpot)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mainObraArteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainObraArteActionPerformed
        // TODO add your handling code here:
        try {
            CrudObraArte coa = new CrudObraArte();
            this.mainDeskpot.add(coa);
            coa.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_mainObraArteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JDesktopPane mainDeskpot;
    private javax.swing.JMenuItem mainObraArte;
    // End of variables declaration//GEN-END:variables
}
