package tallermecanica.Modals;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import tallermecanica.Models.ClienteModel;
import tallermecanica.Models.VehiculoModel;

/**
 *
 * @author adrian
 */
public class AddNewVehiculoModal extends javax.swing.JDialog {

    private VehiculoModel vm;
    private ClienteModel cm;

    /**
     * Creates new form AddNewVehiculoModal hijo de puta soy el wanakin, el
     * paladin rimas de canciones, mano robotica como anakin WOOOO!
     */
    public AddNewVehiculoModal(java.awt.Frame parent, boolean modal) throws ClassNotFoundException, SQLException {
        super(parent, modal);
        initComponents();
        vm = new VehiculoModel();
        cm = new ClienteModel();
        loadComboBoxMarca();
    }

    /**
     * TODO Mostrar las marcas disponibles de los vehiculos
     *
     * @throws SQLException
     */
    public void loadComboBoxMarca() throws SQLException {
        ResultSet r = vm.viewMarca();
        try {
            if (r.next()) {
                r.beforeFirst();
                while (r.next()) {
                    this.jcMarca.addItem(r.getString("nombreMarca"));
                }
            } else {
                JOptionPane.showMessageDialog(null, "No hay marcas registradas", "Error", JOptionPane.WARNING_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtPatente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtModelo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jcMarca = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jtColor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtYear = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtRut = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jlNombre = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jlApellido = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jlEmail = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jlTelefono = new javax.swing.JLabel();
        btnVerificarCliente = new javax.swing.JButton();
        btnAddNew = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar Nuevo Automovil");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Agregar nuevo vehiculo"));

        jLabel1.setText("Patente");

        jLabel2.setText("Marca");

        jLabel3.setText("Modelo");

        jcMarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {""}));

        jLabel4.setText("Color");

        jLabel5.setText("Año");

        jLabel6.setText("Rut Cliente");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Cliente"));

        jLabel7.setText("Nombre");

        jlNombre.setText("[                                 ]");

        jLabel8.setText("Apellido");

        jlApellido.setText("[                                 ]");

        jLabel10.setText("Email");

        jlEmail.setText("[                                 ]");

        jLabel12.setText("Telefono");

        jlTelefono.setText("[                                   ]");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel7))
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlApellido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(208, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jlNombre))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jlApellido))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jlEmail))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jlTelefono))
                .addContainerGap(128, Short.MAX_VALUE))
        );

        btnVerificarCliente.setText("Verificar Cliente");
        btnVerificarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarClienteActionPerformed(evt);
            }
        });

        btnAddNew.setText("Agregar");
        btnAddNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAddNew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtModelo)
                    .addComponent(jtPatente)
                    .addComponent(jtColor)
                    .addComponent(jtYear)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtRut, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnVerificarCliente))
                    .addComponent(jcMarca, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jtPatente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jcMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jtRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnVerificarCliente))))
                .addGap(42, 42, 42)
                .addComponent(btnAddNew)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerificarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarClienteActionPerformed
        // TODO add your handling code here:
        String rut = this.jtRut.getText();
        if (!rut.equals("")) {
            try {

                ResultSet rs = cm.verificarRutExistente(rut);
                if (rs.next()) {
                    rs.beforeFirst();
                    while (rs.next()) {
                        this.jlNombre.setText(rs.getString("nombresCliente"));
                        this.jlApellido.setText(rs.getString("apellidosCliente"));
                        this.jlEmail.setText(rs.getString("emailCliente"));
                        this.jlTelefono.setText(rs.getString("fonoCliente"));
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Rut No registrados", "Error", JOptionPane.WARNING_MESSAGE);
                }
            } catch (SQLException ex) {
                Logger.getLogger(AddNewVehiculoModal.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Rut Requerido!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnVerificarClienteActionPerformed

    /**
     * TODO Agregar un nuevo automovil al sistema
     *
     * @param evt
     */
    private void btnAddNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewActionPerformed
        // TODO add your handling code here:
        String patente = this.jtPatente.getText();
        String marcas = (String) this.jcMarca.getSelectedItem();
        String modelo = this.jtModelo.getText();
        String color = this.jtColor.getText();
        String year = this.jtYear.getText();
        String rut = this.jtRut.getText();
        if (patente.equals("")) {
            JOptionPane.showMessageDialog(null, "Patente Requerida!", "Error", JOptionPane.ERROR_MESSAGE);
            this.jtPatente.requestFocus();
        } else if (marcas.equals("")) {
            JOptionPane.showMessageDialog(null, "Marca Requerida!", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (modelo.equals("")) {
            JOptionPane.showMessageDialog(null, "Modelo Requerido!", "Error", JOptionPane.ERROR_MESSAGE);
            this.jtModelo.requestFocus();
        } else if (color.equals("")) {
            JOptionPane.showMessageDialog(null, "Color Requerido!", "Error", JOptionPane.ERROR_MESSAGE);
            this.jtColor.requestFocus();
        } else if (year.equals("")) {
            JOptionPane.showMessageDialog(null, "Año Requerido!", "Error", JOptionPane.ERROR_MESSAGE);
            this.jtYear.requestFocus();
        } else if (rut.equals("")) {
            JOptionPane.showMessageDialog(null, "Rut Requerido!", "Error", JOptionPane.ERROR_MESSAGE);
            this.jtRut.requestFocus();
        }
        try {
            ResultSet rutVeri = cm.verificarRutExistente(rut);
            if (rutVeri.next()) {
                rutVeri.beforeFirst();
                if (!vm.verificPatente(patente)) {
                    vm.addNewVehiculo(patente, marcas, modelo, color, Integer.parseInt(year), rut);
                    JOptionPane.showMessageDialog(null, "agregado Correctamente", "Success", JOptionPane.INFORMATION_MESSAGE);
                    this.jtPatente.setText("");
                    this.jcMarca.setSelectedIndex(0);
                    this.jtModelo.setText("");
                    this.jtColor.setText("");
                    this.jtYear.setText("");
                    this.jtRut.setText("");
                } else {
                    JOptionPane.showMessageDialog(null, "Patente ya registrada!", "Error", JOptionPane.ERROR_MESSAGE);
                }

            } else {
                JOptionPane.showMessageDialog(null, "Rut No encontrado!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (NullPointerException e) {

        }
    }//GEN-LAST:event_btnAddNewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNewVehiculoModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNewVehiculoModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNewVehiculoModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNewVehiculoModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            AddNewVehiculoModal dialog = null;
            try {
                dialog = new AddNewVehiculoModal(new javax.swing.JFrame(), true);
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(AddNewVehiculoModal.class.getName()).log(Level.SEVERE, null, ex);
            }
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNew;
    private javax.swing.JButton btnVerificarCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> jcMarca;
    private javax.swing.JLabel jlApellido;
    private javax.swing.JLabel jlEmail;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JLabel jlTelefono;
    private javax.swing.JTextField jtColor;
    private javax.swing.JTextField jtModelo;
    private javax.swing.JTextField jtPatente;
    private javax.swing.JTextField jtRut;
    private javax.swing.JTextField jtYear;
    // End of variables declaration//GEN-END:variables
}
