package ventasproductos;

import java.util.ArrayList;
import java.util.HashMap;

/**
 *
 * @author adrian
 */
public class Principal extends javax.swing.JFrame {

    public static ArrayList<Productos> dataProducto = new ArrayList<>();
    public static HashMap<Integer, ArrayList<RegistroVenta>> dataTotalRegistro = new HashMap<>(); 
    public static ArrayList<RegistroVenta> dataRV = new ArrayList<>();
    /**
     *
     */

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        llenarDatoProducto();
    }

    public void llenarDatoProducto() {
        int numero, numero2;
        String[] nombreProducto = {
            "Notebook", "Telefonos", "Lechugas", "Manzanas", "Consolas",
            "Televisores", "Equipos Musicales", "Tomates", "Peras"
        };
        String[] familiaProducto = {
            "LICOR",
            "VEGETALES",
            "FRUTAS",
            "TECNOLOGIA"
        };
        for (int i = 0; i < 30; i++) {
            numero = (int) (Math.random() * nombreProducto.length);
            numero2 = (int) (Math.random() * familiaProducto.length);

            String nombre = nombreProducto[numero];
            String famPro = familiaProducto[numero2];
            FamiliaProducto fp = FamiliaProducto.valueOf(famPro);
            String codigo = nombre + "" + i;
            int costo = (int) (Math.random() * 100);
            Productos p = new Productos(nombre, fp, codigo, costo);
            dataProducto.add(p);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorioVenta = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnIngresarVenta = new javax.swing.JMenuItem();
        jMostraRegistroVenta = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioVentaLayout = new javax.swing.GroupLayout(escritorioVenta);
        escritorioVenta.setLayout(escritorioVentaLayout);
        escritorioVentaLayout.setHorizontalGroup(
            escritorioVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 719, Short.MAX_VALUE)
        );
        escritorioVentaLayout.setVerticalGroup(
            escritorioVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 422, Short.MAX_VALUE)
        );

        jMenu1.setText("File");

        btnIngresarVenta.setText("Ingresar Venta");
        btnIngresarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarVentaActionPerformed(evt);
            }
        });
        jMenu1.add(btnIngresarVenta);

        jMostraRegistroVenta.setText("Lista de Ventas");
        jMostraRegistroVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMostraRegistroVentaActionPerformed(evt);
            }
        });
        jMenu1.add(jMostraRegistroVenta);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("mostrar");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Ventas anuladas");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(escritorioVenta)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(escritorioVenta)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarVentaActionPerformed
        // TODO add your handling code here:
        IngresoVenta iv = new IngresoVenta();
        this.escritorioVenta.add(iv);
        iv.setVisible(true);
    }//GEN-LAST:event_btnIngresarVentaActionPerformed

    private void jMostraRegistroVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMostraRegistroVentaActionPerformed
        // TODO add your handling code here:
        MostrarRegistroVenta mrv = new MostrarRegistroVenta();
        this.escritorioVenta.add(mrv);
        mrv.setVisible(true);
    }//GEN-LAST:event_jMostraRegistroVentaActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        MostrarVentaAnulada v = new MostrarVentaAnulada();
        this.escritorioVenta.add(v);
        v.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnIngresarVenta;
    private javax.swing.JDesktopPane escritorioVenta;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMostraRegistroVenta;
    // End of variables declaration//GEN-END:variables
}
