/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tallermecanica;

import java.awt.Frame;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import tallermecanica.Modals.AddNewUserModal;
import tallermecanica.Models.UsuarioModel;

/**
 *
 * @author adrian
 */
public class CrudUsuarios extends javax.swing.JInternalFrame {

    ResultSet rs;
    DefaultTableModel dm;
    UsuarioModel um;

    /**
     * Creates new form CrudUsuarios
     */
    public CrudUsuarios() throws ClassNotFoundException {
        initComponents();
        dm = new DefaultTableModel();
        um = new UsuarioModel();
        loadDataUsuario();
        this.jlIdentificador.setVisible(false);
    }

    public void loadDataUsuario() {
        String title[] = {"N°", "Nombre", "Email", "Fecha Creacion"};
        dm = new DefaultTableModel(title, 0);
        try {
            ResultSet r = um.viewUser();
            if (r.next()) {
                r.beforeFirst();
                while (r.next()) {
                    String number = r.getString("idUsuario");
                    String nombre = r.getString("nombreUsuario");
                    String email = r.getString("EmailUsuario");
                    String fechCreacion = r.getString("fechaCreacionUsuario");
                    Object data[] = {number, nombre, email, fechCreacion};
                    dm.addRow(data);
                }
                this.jtDataUser.setModel(dm);
            } else {
                JOptionPane.showMessageDialog(null, "No hay Registros!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPopUp = new javax.swing.JPopupMenu();
        jmEliminar = new javax.swing.JMenuItem();
        jmEditar = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtDataUser = new javax.swing.JTable();
        btnRefrescar = new javax.swing.JButton();
        btnAddNewUser = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtNombre = new javax.swing.JTextField();
        jtEmail = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();
        jlIdentificador = new javax.swing.JLabel();

        jmEliminar.setText("Eliminar");
        jmEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmEliminarActionPerformed(evt);
            }
        });
        mainPopUp.add(jmEliminar);

        jmEditar.setText("Editar");
        jmEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmEditarActionPerformed(evt);
            }
        });
        mainPopUp.add(jmEditar);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jtDataUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtDataUser.setComponentPopupMenu(mainPopUp);
        jScrollPane1.setViewportView(jtDataUser);

        btnRefrescar.setText("Refrescar");
        btnRefrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefrescarActionPerformed(evt);
            }
        });

        btnAddNewUser.setText("Agregar nuevo");
        btnAddNewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewUserActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Edicion de usuarios"));

        jLabel1.setText("Nombre");

        jLabel2.setText("Email");

        btnActualizar.setText("Guardar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        jlIdentificador.setText("jLabel4");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtEmail)
                    .addComponent(jtNombre)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addComponent(jlIdentificador)
                .addContainerGap(172, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlIdentificador))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnActualizar)))
                .addContainerGap(116, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRefrescar)
                .addGap(18, 18, 18)
                .addComponent(btnAddNewUser)
                .addGap(164, 164, 164))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 520, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefrescar)
                    .addComponent(btnAddNewUser))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefrescarActionPerformed
        // TODO add your handling code here:
        loadDataUsuario();
        JOptionPane.showMessageDialog(null, "Tabla Actualizada!", "Info", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnRefrescarActionPerformed

    /**
     * TODO llamar al jDialog de agregar nuevo usuario;;
     *
     * @param evt
     */
    private void btnAddNewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewUserActionPerformed
        // TODO add your handling code here:
        try {
            Frame frame = new Frame();
            AddNewUserModal a = new AddNewUserModal(frame, true);
            a.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddNewUserActionPerformed

    /**
     * TODO Eliminar usuarios
     *
     * @param evt
     */
    private void jmEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmEliminarActionPerformed
        // TODO add your handling code here:
        try {
            int reg = this.jtDataUser.getSelectedRow();
            int confirm = JOptionPane.showConfirmDialog(null, "¿Estas Seguro de eliminarlo?");
            if (JOptionPane.OK_OPTION == confirm) {
                String ident = (String) this.jtDataUser.getValueAt(reg, 0);
                um.deleteUser(Integer.parseInt(ident));
                JOptionPane.showMessageDialog(null, "Eliminado con exito", "success", JOptionPane.INFORMATION_MESSAGE);
                loadDataUsuario();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jmEliminarActionPerformed

    /**
     * TODO actualizar datos del usuario
     *
     * @param evt
     */
    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        try {
            String n = this.jtNombre.getText();
            String e = this.jtEmail.getText();
            String i = this.jlIdentificador.getText();
            if(n.equals("")) {
                JOptionPane.showMessageDialog(null, "Nombre Requerido !", "Error", JOptionPane.ERROR_MESSAGE);
                this.jtNombre.requestFocus();
            } else if (e.equals("")) {
                JOptionPane.showMessageDialog(null, "Email Requerido !", "Error", JOptionPane.ERROR_MESSAGE);
                this.jtEmail.requestFocus();
            } else {
                um.updateUser(Integer.parseInt(i), n, e);
                JOptionPane.showMessageDialog(null, "Editado con exito!", "Success", JOptionPane.INFORMATION_MESSAGE);
                loadDataUsuario();
                this.jtNombre.setText("");
                this.jtEmail.setText("");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnActualizarActionPerformed
    
    /**
     * TODO Settiar datos para actualizar los datos
     * @param evt 
     */
    private void jmEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmEditarActionPerformed
        // TODO add your handling code here:
        try {
            int reg = this.jtDataUser.getSelectedRow();
            String id = (String) this.jtDataUser.getValueAt(reg, 0);
            String nombre = (String) this.jtDataUser.getValueAt(reg, 1);
            String email = (String) this.jtDataUser.getValueAt(reg, 2);
            this.jtNombre.setText(nombre);
            this.jtEmail.setText(email);
            this.jlIdentificador.setText(id);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jmEditarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAddNewUser;
    private javax.swing.JButton btnRefrescar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlIdentificador;
    private javax.swing.JMenuItem jmEditar;
    private javax.swing.JMenuItem jmEliminar;
    private javax.swing.JTable jtDataUser;
    private javax.swing.JTextField jtEmail;
    private javax.swing.JTextField jtNombre;
    private javax.swing.JPopupMenu mainPopUp;
    // End of variables declaration//GEN-END:variables
}
